; Reference:
; Intel® 64 and IA-32 Architectures Software Developer’s Manual Vol3 6-13

; Trap is handled like a sandwich, there are three stages:
;   | trapgo
;   | trap
;   | trapret
;
; An new interrupt calls vector{n} handler in vectors.s
; (generated by vectors.py), which first push the trap
; number to the stack, then jump to `trapgo`.
;
; `trapgo` will setup the TrapFrame, then jump to `trap`
; which handles the interrupt. the TrapFrame contains
; a snapshot of the current CPU stage and trapno. This
; information are important for `trap`.
;
; After `trap` is finished, it will yield the conrtrol
; back to the scheduler. Which means the stack is switched
; from the process kernel stack to the global kernel stack.
;
; At this point, the process is suspended, the TrapFrame
; still remains in the process kernel stack.
;
; The process is in READY state. When next time the scheduler
; picks it up, the TrapFrame is still on the stack, and the
; eip was saved to `trapret`
;
; `trapret` restore all saved registers and resume from the
; saved $eip. The $eip is saved by the hardware when the interrupt
; happened.
;
; Trap the heartbeat of the Kernel, this process runs thousands
; of times per timer tick for every event happens in the system.


extern trap

; ------------------------------
; Enter the trap
;
global trapgo
trapgo:
    ; When cpu calls the interrupt handler, the CPU will
    ; switch to the kernel stack via TSS, then save the following
    ; information on the stack:
    ;
    ;        ..0x0
    ;        +---------------------+
    ; esp -> | errcode             |
    ;        | eip                 |
    ;        | cs                  |
    ;        | eflags              |
    ;        | esp                 | (Only if privilege changed)
    ; esp0-> | ss                  | (Only if privilege changed)
    ;        +---------------------+
    ;
    ; Then it will invoke trapgo, where we do the following:
    push ds
    push es
    push fs
    push gs
    pusha

    ; Now the stack is setup like this:
    ;
    ;        ..0x0
    ;        +---------------------+
    ; esp -> | EDI, ESI, EBP, ...  | (Registers saved by `pusha`)
    ;        | DS, ES, FS, GS      | (Segment registers)
    ;        | trapno              |
    ;        +---------------------+  Hardware context
    ;        | errcode             |
    ;        | eip                 |
    ;        | cs                  |
    ;        | eflags              |
    ;        | esp                 | (Only if privilege changed)
    ; esp0-> | ss                  | (Only if privilege changed)
    ;        +---------------------+
    ;
    ; Where $esp is interpreted as (TrapFrame *)


; ------------------------------
; C FFI to calls void trap(TrapFrame *)
    push esp
    call trap
    add esp, 0x4 ; clear up the argument pushed.


; ------------------------------
; Fall through
; `trapret` restore the context before the trap.
global trapret
trapret:
    popa         ; restore all saved general purpose registers
    pop gs       ; restore segment registers
    pop fs
    pop es
    pop ds
    add esp, 0x8 ; skip trapno and errcode so it points to $eip
    ; At this point the stack looks like this:
    ;        ..0x0
    ;        +------------------------+
    ;        | trapno                 |
    ;        +------------------------+  Hardware context
    ;        | errcode                |
    ; esp -> | eip                    |
    ;        | cs                     |
    ;        | eflags                 |
    ;        | esp                    |
    ; esp0-> | ss                     |
    ;        +------------------------+
    ;
    ; iret returns from the interrupt handler, if
    ; $cs has DLP=3, it will switch stack and drop the
    ; CPU back to user space.
    iret
