#!/bin/bash
# remove cpp comments

while read -r line; do
    if [[ "${line:0:1}" == "#" ]]; then continue; fi
    if [[ "${line:0:2}" == "//"  ]]; then continue; fi
    if [[ -z "${line}" ]]; then continue; fi
    echo $line
done
