#!/usr/bin/env bash

# Start picocom

# wait until the virtual-tty is created
printf "[\033[32mSerial\033[0m] waiting for /tmp/virtual-tty...\n"
while [ ! -e /tmp/virtual-tty ]; do sleep 0.1; done
printf "[\033[32mSerial\033[0m] found.\n"
picocom --echo --escape C-c --flow n --imap lfcrlf  /tmp/virtual-tty
